#!/bin/bash
trap "wait" TERM EXIT

# Big Buck Bunny - 200ms RTT
nice python plot_vlc_scatters.py two_con_scatters_bbb_200ms_classic_keepalive.png tests/constant_two_con_bbb8_200ms_200p/*_classic-13_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bbb_200ms_classic_keepalive_est.png tests/constant_two_con_bbb8_200ms_200p/*_classic-13_keepalive_est &
nice python plot_vlc_scatters.py two_con_scatters_bbb_200ms_bba0_keepalive.png tests/constant_two_con_bbb8_200ms_200p/*_bba0_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bbb_200ms_bba1_keepalive_est.png tests/constant_two_con_bbb8_200ms_200p/*_bba1_keepalive_est &
wait
# Big Buck Bunny - 100ms RTT
nice python plot_vlc_scatters.py two_con_scatters_bbb_100ms_classic_keepalive.png tests/constant_two_con_bbb8_100ms_200p/*_classic-13_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bbb_100ms_classic_keepalive_est.png tests/constant_two_con_bbb8_100ms_200p/*_classic-13_keepalive_est &
nice python plot_vlc_scatters.py two_con_scatters_bbb_100ms_bba0_keepalive.png tests/constant_two_con_bbb8_100ms_200p/*_bba0_keepalive_est &
nice python plot_vlc_scatters.py two_con_scatters_bbb_100ms_bba1_keepalive_est.png tests/constant_two_con_bbb8_100ms_200p/*_bba1_keepalive_est &
wait
# Big Buck Bunny - 400ms RTT
nice python plot_vlc_scatters.py two_con_scatters_bbb_400ms_classic_keepalive.png tests/constant_two_con_bbb8_400ms_200p/*_classic-13_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bbb_400ms_classic_keepalive_est.png tests/constant_two_con_bbb8_400ms_200p/*_classic-13_keepalive_est &
nice python plot_vlc_scatters.py two_con_scatters_bbb_400ms_bba0_keepalive.png tests/constant_two_con_bbb8_400ms_200p/*_bba0_keepalive_est &
nice python plot_vlc_scatters.py two_con_scatters_bbb_400ms_bba1_keepalive_est.png tests/constant_two_con_bbb8_400ms_200p/*_bba1_keepalive_est &
wait

# BipBop
nice python plot_vlc_scatters.py two_con_scatters_bipbop_200ms_classic_keepalive.png tests/constant_two_con_bipbop_200ms_200p/*_classic-2_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bipbop_200ms_classic_keepalive_est.png tests/constant_two_con_bipbop_200ms_200p/*_classic-2_keepalive_est &
wait
nice python plot_vlc_scatters.py two_con_scatters_bipbop_200ms_bba0_keepalive.png tests/constant_two_con_bipbop_200ms_200p/*_bba0_keepalive &
nice python plot_vlc_scatters.py two_con_scatters_bipbop_200ms_bba1_keepalive.png tests/constant_two_con_bipbop_200ms_200p/*_bba1_keepalive_est &
wait

